### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by stadibo** [Kalakuh/tiralabra#1]
#### Rakenne
Toteutuksen kannalta koodin yleinen rakenne näyttää erittäin järkevältä. Varsinkin binääripuun toteutus muiden puurakenteiden runkona vaikuttaa toimivan hyvin. Tämä johtaa mahdollisesti yleisiin metodi nimiin, jotka eivät välttämättä kuvailisi toimintaa laajentavissa luokissa, mutta tässä abstraktio on toimiva. Metodien nimeäminen on selkeätä, eikä mikään varsin epäselvä muuttujanimi iskenyt silmään.

#### Parannusehdotuksia
Itse tietorakenteissa en löytänyt mitään erittäin kummallista. Ehkä *ScapegoatTree* luokan **insertHelper** metodi on pitkähkö, mutta sen ositus ei tarvitse olla prioriteetti. Luokan toteutus taitaa olla kahdesta muusta puusta niin eroava, että suoraan binääripuun laajentaminen on haastavampaa.

Suorituskykytestauksessa, joka on aluillaan, löytyi muutama huomioitava asia: **test.java**

**1.**
```
private boolean contains(BinaryTree<Integer> tree, Integer key, HashMap<Integer, Integer> map) {
if (!map.containsKey(key)) {
            map.put(key, 0);
        }
        **if ((map.get(key) != 0) != tree.contains(key)) {
            return false;
        }
        return true;**
    }
```
( ((map.get(key) != 0) => false) != (tree.contains(key) => false) ) => false, ja metodi palauttaa true. Mikä ei taida olla toivottu tulos, kun puu ei sisällä avainta. Jompi kumpi “!=“ tulisi muuttaa muotoon “==”.

**2:**
**erase** metodi taitaa olla vain copy paste **insert** metodista (eli testeissä ei koskaan poisteta), ja olet ehkä tietoinen tästä, mutta huomioin tämän muistutuksena :)

**3:**
**run** metodissa, joka varmasti vielä muuttuu, voisi koodin luettavuuden kannalta muuttaa ehtolausekkeet “switch statement”:iksi, joka vähentäisi koodin toistuvuutta.

**4:**
Suorituskykytestauksessa olisi kiinnostavaa testata syntipukkipuuta erilaisilla alpha arvoilla, miten se vaikuttaa eri operaatioihin. Ja yleisesti miten eri operaatioiden suoritus vaihtelee puiden välillä.

*Tähän mennessä hyvää duunia! Toivottavasti saat ongelmakohdat ratkaistua.*

**Comment by hjuha** [comment]
**1.**
Kiitos huomiosta. Oikeastaan kyseessä on huonosti nimetty funktio: alun perin kaikki koodi oli samassa funktiossa, ja tuon osan oli tarkoitus tarkistaa, että binääripuun `contains` varmasti palauttaa oikean arvon. Kun tästä testauksesta tehtiin erillinen funktio, niin sen nimeksi jäi contains, mikä ei varsinaisesti kuvaa funktion tehtävää.

Tämä kohta kaipaa muutenkin kyllä elegantimpaa toteutusta.

**2.**
Kappas, tämäpä kiusallista. Huolimattomuuksissani olen kopioinut väärän koodipätkän tähän koodin siistimisen yhteydessä, eikä asialle ollut sen havaitsevaa testausta.

**3.**
Olet oikeassa. Alun perin siinä oli switch, mutta Checkstyle suositteli liian pitkän funktion lyhentämistä, jotta koodi selkeytyisi. Todellisuudessa oli vähän kyseenalainen ratkaisu vaihtaa sellainen pois if-else-rakenteeksi.

**4.**
Tämä on hyvä pointti, ja tämä tulee toteutettua mikäli aikaa jää yhtään ylimääräistä.

_Kiitos palautteesta, siitä oli suuri apu._
